app = "pie-gd-elasticsearch"
primary_region = "sea"

[env]
  PRIMARY_REGION = "sea"
  ES_JAVA_OPTS = "-Xms1024m -Xmx1024m -Des.enforce.bootstrap.checks=true"
  "cluster.name" = "es-mastodon"
  "discovery.type" = "single-node"
  "thread_pool.write.queue_size" = "1000"
  "xpack.graph.enabled" = "false"
  "xpack.license.self_generated.type" = "basic"
  "xpack.ml.enabled" = "false"
  "xpack.security.enabled" = "false"
  "xpack.watcher.enabled" = "false"

[mounts]
  source = "mastodon_elasticsearch"
  destination = "/usr/share/elasticsearch/data"

[http_service]
  internal_port = 9200
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[checks]
  [checks.es]
    type = "http"
    port = 9200
    path = "/_cluster/health"
    grace_period = "15s"
    interval = "5s"
    restart_limit = 8
    timeout = "4s"
