app = "pie-gd-mastodon-v2"
primary_region = "sea"

[build]
  dockerfile = "apps/mastodon/Dockerfile"

# [deploy]
#   release_command = "bundle exec rails db:migrate"

[env]
  MAX_THREADS = "10"
  RAILS_LOG_LEVEL = "warn"
  RAILS_LOG_TO_STDOUT = "true"
  RAILS_SERVE_STATIC_FILES = ""
  STATSD_ADDR = "localhost:9125"
  WEB_CONCURRENCY = "0"

[metrics]
  port = 9091
  path = "/metrics"

[processes]
  mastodon = "hivemind Procfile.mastodon"
  sidekiq = "hivemind Procfile.sidekiq"

[[services]]
  internal_port = 8080 # Caddy listens on 8080 and proxies to Rails on port 3000 and Node on port 4000
  processes = ["mastodon"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 200
    soft_limit = 50
    type = "requests"

  [[services.http_checks]]
    path = "/health"
    grace_period = "10s"
    interval = "15s"
    restart_limit = 8
    timeout = "2s"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
