app = "pie-gd-mastodon-v2"
kill_timeout = 15
primary_region = "sea"

[build]
  dockerfile = "apps/mastodon/Dockerfile"

[deploy]
  strategy = "bluegreen"

  # When it's necessary to run DB migrations before a deployment, uncomment the
  # following line.
  # release_command = "bundle exec rails db:migrate"

[env]
  #HEADER_CLIENT_IP = "cf-connecting-ip" # Trust Cloudflare's cf-connecting-ip header
  MAX_THREADS = "16"
  MIN_THREADS = "5"
  RAILS_LOG_LEVEL = "warn"
  RAILS_LOG_TO_STDOUT = "true"
  RAILS_SERVE_STATIC_FILES = ""
  STATSD_ADDR = "localhost:9125"
  WEB_CONCURRENCY = "0"

[metrics]
  port = 9091
  path = "/metrics"

[processes]
  mastodon = "hivemind --timeout 10 Procfile.mastodon"
  sidekiq = "hivemind --timeout 10 Procfile.sidekiq"

[[services]]
  internal_port = 8080 # Caddy listens on 8080 and proxies to Rails on port 3000 and Node on port 4000
  processes = ["mastodon"]
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1

  [services.concurrency]
    hard_limit = 400
    soft_limit = 200
    type = "requests"

  [[services.http_checks]]
    path = "/health"
    grace_period = "15s"
    interval = "10s"
    restart_limit = 8
    timeout = "2s"

  [[services.http_checks]]
    path = "/api/v1/streaming/health"
    grace_period = "15s"
    interval = "10s"
    restart_limit = 8
    timeout = "2s"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
