# fly.toml file generated for pie-gd-postgres on 2023-03-21T20:51:48-07:00

app = "pie-gd-postgres"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"

[env]
  PRIMARY_REGION = "sea"

[metrics]
  port = 9187
  path = "/metrics"

[mounts]
  source = "pg_data"
  destination = "/data"

[checks]
  [checks.pg]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/pg"
  [checks.role]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/role"
  [checks.vm]
    port = 5500
    type = "http"
    interval = "1m0s"
    timeout = "10s"
    path = "/flycheck/vm"
