app = "pie-gd-postgres15"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"
swap_size_mb = 1024

[env]
  PRIMARY_REGION = "sea"

[[vm]]
  size = "shared-cpu-1x"
  memory = 512

[metrics]
  port = 9187
  path = "/metrics"

[mounts]
  source = "pg_data"
  destination = "/data"
  auto_extend_size_threshold = 60
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "50GB"

[checks]
  [checks.pg]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/pg"

  [checks.role]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/role"

  [checks.vm]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/vm"

[[services]]
  protocol = "tcp"
  internal_port = 5432

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[services]]
  protocol = "tcp"
  internal_port = 5433

  [[services.ports]]
    port = 5433
    handlers = ["pg_tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
