app = "pie-gd-redis"
swap_size_mb = 512

[deploy]
  strategy = "rolling"

[env]
  PRIMARY_REGION = "sea"

[metrics]
  port = 9091
  path = "/metrics"

[mounts]
  source = "mastodon_redis"
  destination = "/data"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "10GB"
